// Get all persons
GET http://localhost:3001/api/persons

###
// Get page info
GET http://localhost:3001/info

###
// Get single person
GET http://localhost:3001/api/persons/5d785e240bd77e2d62c8f0c4

###
// Delete person
DELETE http://localhost:3001/api/persons/5d791a305b0d25350416630c

###
// Change persons number
PUT http://localhost:3001/api/persons/5d785e240bd77e2d62c8f0c4
Content-Type: application/json

{
    "name": "Joaquin",
    "number": "11 5311 8877"
}

###
// Add new person
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "ESTE SI!!!!",
    "number": "11 5311 8877"
}